name: BUG
description: Submit a Bug report!!!!!
title: "🐞 [BUG]: "
body:
  - type: markdown
    attributes: 
      value: Thank you for taking the time to fill out this BUG report!!!!!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed introduction to the BUG and the reason why you consider it to be a BUG!!!!!
      placeholder: Description and Reason
  - type: markdown
    attributes:
      value: ---
  - type: input
    id: descsep
    attributes:
      label: ---
      description: This will be used as a SEPERATOR in the markdown. KINDLY DO NOT CHANGE THE VALUE.
      value: ---
    validations:
      required: true
