name: BUG
description: Submit a BUG Report!!!!!
title: "🐞 [BUG]: "
body:
  - type: markdown
    attributes:
      value: |
        ---
  - type: markdown
    attributes:
      value: |
        *THANK YOU FOR TAKING THE TIME TO FILL OUT THIS BUG REPORT FORM!!!!!*
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: description
    attributes:
      label: |
        Description
      description: |
        *Provide a detailed information of the BUG and the reason why you consider it to be a BUG!!!!!*
      placeholder: |
        BUG's description and the reason.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: descsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        *This will be used as a SEPERATOR in the markdown.* ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: expbeh
    attributes:
      label: |
        Expected Behaviour
      description: |
        *Tell us what should happen!!!!!*
      placeholder: |
        Description of the Expected Behaviour.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: exbhsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        *This will be used as a SEPERATOR in the markdown.* ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: actbeh
    attributes:
      label: |
        Actual Behaviour
      description: |
        *Tell us what happens instead!!!!!*
      placeholder: |
        Description of the Actual Behaviour.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: acbhsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        *This will be used as a SEPERATOR in the markdown.* ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: steps
    attributes:
      label: |
        Steps to Reproduce
      description: |
        *Provide the set of Steps to reproduce the BUG!!!!!*

        *(TO BE PROVIDED IN BELOW FORMAT)*
        ***Steps to Reproduce the BUG
        1.
        2.
        3.***
      placeholder: |
        Provide Steps in above Format.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: stepsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        *This will be used as a SEPERATOR in the markdown.* ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: screenshot
    attributes:
      label: |
        BUG Screenshot
      description: |
        *Provide the Screenshot of the BUG!!!!!*
      placeholder: |
        Link of the Screenshot.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: scshsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        *This will be used as a SEPERATOR in the markdown.* ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: log
    attributes:
      label: |
        BUG Code or Logs (If Applicable)
      description: |
        *Include the code to reproduce, if relevant or the output!!!!!*
      placeholder: |
        Code or Log generated.
      render: VBA
    validations:
      required: false
