name: BUG
description: SUBMIT A BUG REPORT!!!!!
title: "🐞 [BUG]: "
body:
  - type: markdown
    attributes:
      value: |
        ---
  - type: markdown
    attributes:
      value: |
        ###### THANK YOU FOR TAKING THE TIME TO FILL OUT THIS BUG REPORT FORM!!!!!
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: description
    attributes:
      label: |
        Description
      description: |
        ###### KINDLY PROVIDE A DETAILED INFORMATION OF THE BUG AND THE REASON WHY YOU CONSIDER IT TO BE A BUG!!!!!
      placeholder: |
        Describe the BUG and the reason.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: descsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        ###### THIS WILL BE USED AS A SEPARATOR IN THE MARKDOWN.
        ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: expbeh
    attributes:
      label: |
        Expected Behaviour
      description: |
        ###### Kindly provide the details of what should happen!!!!!
      placeholder: |
        Describe the Expected Behaviour.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: exbhsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        ###### THIS WILL BE USED AS A SEPARATOR IN THE MARKDOWN.
        ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: actbeh
    attributes:
      label: |
        Actual Behaviour
      description: |
        ###### KINDLY PROVIDE THE DETAILS OF WHAT HAPPENS INSTEAD!!!!!
      placeholder: |
        Describe the Actual Behaviour.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: acbhsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        ###### THIS WILL BE USED AS A SEPARATOR IN THE MARKDOWN.
        ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: steps
    attributes:
      label: |
        Steps to Reproduce
      description: |
        ###### KINDLY PROVIDE THE SET OF STEPS TO REPRODUCE THE BUG!!!!!

        ***(TO BE PROVIDED IN THE BELOW FORMAT ONLY)***
        ```
        Steps to Reproduce the BUG
        1.
        2.
        3.
        ```
      placeholder: |
        Describe the steps in above format.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: stepsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        ###### THIS WILL BE USED AS A SEPARATOR IN THE MARKDOWN.
        ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: screenshot
    attributes:
      label: |
        BUG Screenshot
      description: |
        ###### KINDLY PROVIDE THE SCREENSHOT OF THE BUG!!!!!
      placeholder: |
        Upload the screenshot image.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: scshsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        ###### THIS WILL BE USED AS A SEPARATOR IN THE MARKDOWN.
        ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: log
    attributes:
      label: |
        BUG Code or Logs (If Applicable)
      description: |
        ###### KINDLY PROVIDE THE CODE TO REPRODUCE OR THE LOG OUTPUT!!!!!
      placeholder: |
        Code or Log generated.
      render: VBA
    validations:
      required: false
