name: BUG
description: Submit a Bug report!!!!!
title: "🐞 [BUG]: "
body:
  - type: markdown
    attributes: 
      value: Thank you for taking the time to fill out this BUG report!!!!!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed introduction to the BUG and the reason why you consider it to be a BUG!!!!!
      placeholder: Description and Reason
  - type: markdown
    attributes:
      value: ---
  - type: input
    id: descsep
    attributes:
      label: --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: This will be used as a SEPERATOR in the markdown. KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.
      value: ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Tell us what should happen!!!!!
      placeholder: Description of the behavior that is expected
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: input
    id: exbhsep
    attributes:
      label: --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: This will be used as a SEPERATOR in the markdown. KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.
      value: ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Tell us what happens instead!!!!!
      placeholder: Description of the behavior that is actually happening
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: input
    id: acbhsep
    attributes:
      label: --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: This will be used as a SEPERATOR in the markdown. KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.
      value: ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
