name: Feature Request
description: Submit a Feature Request
title: "[Feature]: "
labels: feature
assignees:
  - leovipin1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature Request Form!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the feature that is being requested
      placeholder: Tell us what you want to see!
    validations:
      required: true
  - type: textarea
    id: userstories
    attributes:
      label: User Stories required for this Feature
      description: Kindly specify the list of User Stories that will be worked upon for this feature to be Completed
      placeholder: |
        List of User Stories in Tasklist format
        - [ ] #3 ex.
        - [ ] #15 ex.
        - [ ] #17 ex.
    validations:
      required: true
