name: Feature Request
description: Submit a Feature Request!!!!!
title: "✨ [Feature]: "
labels: feature, incomplete
assignees:
  - leovipin1
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this Feature Request Form!!!!!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed Description of the Feature that is being requested!!!!!
      placeholder: Tell us what you want to see
      value: |
        Tell us what you want to see
        
        
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: userstories
    attributes:
      label: Related User Stories
      description: The list of User Stories for this Feature!!!!!
      value: |
        List of User Stories
        - [ ] #[User Story]
        - [ ] #[User Story]
        - [ ] #[User Story]
    validations:
      required: true
