name: MISCELLANEOUS
description: SUBMIT A REQUEST WHICH CANNOT BE CATEGORISED IN ANY OF OTHER ISSUE TYPES!!!!!
title: "🤔 [Misc]: "
body:
  - type: markdown
    attributes:
      value: |
        ---
  - type: markdown
    attributes:
      value: |
        <em>###### THANK YOU FOR TAKING TIME TO FILL OUT THE REQUEST FORM!!!!!</em>
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: description
    attributes:
      label: |
        Description
      description: |
        *Kindly provide a detailed description of what needs to be done!!!!!*
      placeholder: |
        Describe the work in detail.
    validations:
      required: true
