name: walla
description: walla
title: "📝 [walla]: "
labels: task
assignees:
  - leovipin1
body:
  - type: input
    id: userstory
    attributes:
      label: Related User Story
      description: Specify the User Story to which this Task is Related
    validations:
      required: true
