name: User Story
description: Submit a User Story!!!!!
title: "📇 [UserStory]: "
labels: user story, incomplete
assignees:
  - leovipin1
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this User Story Form!
  - type: textarea
    id: feature
    attributes:
      label: Related Feature
      description: Specify the Feature to which this User Story is Related!!!!!
      placeholder: Enter the User Story Number
      value: |
        - #[Feature]
        
        
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Sumamry of the User Story!!!!!
      placeholder: Summary of the User Story
      value: |
        ########################################
        ***User Story Summary:***
        **As a** *[user concerned by the story]*
        
        **I want** *[goal of the story]*
        
        **so that** *[reason for the story]*
        ########################################
        
        ***User Story Description:***
        A detailed description of the User Story
        
        
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: tasks
    attributes:
      label: Related Tasks
      description: The list of Tasks for this User Story!!!!!
      value: |
        List of Tasks
        - [ ] #[Task]
        - [ ] #[Task]
        - [ ] #[Task]
    validations:
      required: true
