name: issue-automation

on:
  issues:
    types: [assigned]
  pull_request:
    types: [assigned]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: assigned labeling
        uses: andymckay/labeler@master
        with:
          add-labels: in progress
          remove-labels: incomplete
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
