name: Label Commands
on:
  pull_request:
    types: closed
  issues:
    types: closed
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/label-commands@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          CONFIG_FILE: .github/label-commands.yml
