name: Add Label

on:
  issues:
    types: closed

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-ecosystem/action-add-labels@main
        with:
          labels: completed
