name: Add Pull Request Reviewer

on:
  pull_request:
    types:
      - opened

jobs:
  add-reviewer-pr:
    name: Apply PR reviewer
    runs-on: ubuntu-latest
    steps:
      - uses: leovipin1/add-reviewer-pr@master
        with: 
          reviewers: "adpleovipin1"
          token: ${{ secrets.ADD_TO_PROJECT_PAT }}
