name: Add Reviewers

on:
  pull_request:
    types:
      - opened

jobs:
  add-reviewer:
    name: Add Reviewers
    runs-on: ubuntu-latest
    steps:
      - uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          reviewers: adpleovipin1
          re-request-when-approved: true
          re-request-when-changes-requested: true
