name: issue-automation

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: completed
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
