name: Labels Test

on:
  pull_request:
    types:
      - opened
jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      # follows semantic versioning. Lock to different version: v1, v1.5, v1.5.0 or use a commit hash.
      - uses: fuxingloh/multi-labeler@v2.0.3
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }} # optional, default to '${{ github.token }}'  
          config-path: .github/labeler.yml # optional, default to '.github/labeler.yml'
