name: Add Milestone
on:
  issues:
    types: opened

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: guguducken/milestone-add-action@v0.0.1
        with:
          action-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          co-milestones: >
            {
              "[Bug]":"bug",
              "[Feature]":"test"
            }
