on:
  issues:
    types:
      - assigned
  pull_request:
    types:
      - assigned

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to developing
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          user: leovipin1
          # organization: sample-org
          project_id: 13
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Developing # Target status
