name: "Set Issue Label"
on:
  issues_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Amwam/issue-comment-action@vmaster
        with:
          keywords: '["Rejected"]'
          labels: '["rejected"]'
          github-token: "${{ secrets.ADD_TO_PROJECT_PAT }}"
